# generated by tailtest, review before committing
import hashlib
import sqlite3
import time

import jwt
import pytest

from apps_dev.webclaw.api.auth.jwt_utils import (
    ACCESS_TOKEN_EXPIRY,
    ALGORITHM,
    REFRESH_TOKEN_EXPIRY,
    create_access_token,
    create_refresh_token,
    get_signing_secret,
    hash_token,
    verify_token,
)


SECRET = "testsecret1234567890abcdef123456"
USER_ID = "user-abc-123"
EMAIL = "test@example.com"


@pytest.fixture
def mem_db():
    conn = sqlite3.connect(":memory:")
    conn.execute(
        "CREATE TABLE webclaw_config (key TEXT PRIMARY KEY, value TEXT NOT NULL)"
    )
    conn.commit()
    return conn


class TestGetSigningSecret:
    def test_generates_secret_on_first_call(self, mem_db):
        secret = get_signing_secret(mem_db)
        assert isinstance(secret, str)
        assert len(secret) == 64  # 32 bytes hex

    def test_stores_secret_in_db(self, mem_db):
        secret = get_signing_secret(mem_db)
        row = mem_db.execute(
            "SELECT value FROM webclaw_config WHERE key = 'jwt_secret'"
        ).fetchone()
        assert row is not None
        assert row[0] == secret

    def test_returns_same_secret_on_second_call(self, mem_db):
        first = get_signing_secret(mem_db)
        second = get_signing_secret(mem_db)
        assert first == second

    def test_returns_existing_secret_from_db(self, mem_db):
        mem_db.execute(
            "INSERT INTO webclaw_config (key, value) VALUES ('jwt_secret', 'presetsecret')"
        )
        mem_db.commit()
        secret = get_signing_secret(mem_db)
        assert secret == "presetsecret"


class TestCreateAccessToken:
    def test_returns_string(self):
        token = create_access_token(USER_ID, EMAIL, SECRET)
        assert isinstance(token, str)

    def test_payload_contains_expected_claims(self):
        token = create_access_token(USER_ID, EMAIL, SECRET)
        payload = jwt.decode(token, SECRET, algorithms=[ALGORITHM])
        assert payload["sub"] == USER_ID
        assert payload["email"] == EMAIL
        assert payload["type"] == "access"
        assert "jti" in payload
        assert "iat" in payload
        assert "exp" in payload

    def test_expiry_is_15_minutes(self):
        token = create_access_token(USER_ID, EMAIL, SECRET)
        payload = jwt.decode(token, SECRET, algorithms=[ALGORITHM])
        delta = payload["exp"] - payload["iat"]
        assert delta == int(ACCESS_TOKEN_EXPIRY.total_seconds())

    def test_each_token_has_unique_jti(self):
        t1 = create_access_token(USER_ID, EMAIL, SECRET)
        t2 = create_access_token(USER_ID, EMAIL, SECRET)
        p1 = jwt.decode(t1, SECRET, algorithms=[ALGORITHM])
        p2 = jwt.decode(t2, SECRET, algorithms=[ALGORITHM])
        assert p1["jti"] != p2["jti"]


class TestCreateRefreshToken:
    def test_returns_tuple_of_two_strings(self):
        result = create_refresh_token(USER_ID, SECRET)
        assert isinstance(result, tuple)
        assert len(result) == 2
        raw, token_hash = result
        assert isinstance(raw, str)
        assert isinstance(token_hash, str)

    def test_raw_token_is_valid_jwt(self):
        raw, _ = create_refresh_token(USER_ID, SECRET)
        payload = jwt.decode(raw, SECRET, algorithms=[ALGORITHM])
        assert payload["sub"] == USER_ID
        assert payload["type"] == "refresh"

    def test_hash_matches_raw_token(self):
        raw, token_hash = create_refresh_token(USER_ID, SECRET)
        assert token_hash == hashlib.sha256(raw.encode()).hexdigest()

    def test_expiry_is_7_days(self):
        raw, _ = create_refresh_token(USER_ID, SECRET)
        payload = jwt.decode(raw, SECRET, algorithms=[ALGORITHM])
        delta = payload["exp"] - payload["iat"]
        assert delta == int(REFRESH_TOKEN_EXPIRY.total_seconds())


class TestVerifyToken:
    def test_valid_access_token_returns_payload(self):
        token = create_access_token(USER_ID, EMAIL, SECRET)
        payload = verify_token(token, SECRET, expected_type="access")
        assert payload is not None
        assert payload["sub"] == USER_ID

    def test_valid_refresh_token_returns_payload(self):
        raw, _ = create_refresh_token(USER_ID, SECRET)
        payload = verify_token(raw, SECRET, expected_type="refresh")
        assert payload is not None
        assert payload["sub"] == USER_ID

    def test_wrong_type_returns_none(self):
        token = create_access_token(USER_ID, EMAIL, SECRET)
        result = verify_token(token, SECRET, expected_type="refresh")
        assert result is None

    def test_wrong_secret_returns_none(self):
        token = create_access_token(USER_ID, EMAIL, SECRET)
        result = verify_token(token, "wrongsecret", expected_type="access")
        assert result is None

    def test_malformed_token_returns_none(self):
        result = verify_token("not.a.token", SECRET, expected_type="access")
        assert result is None

    def test_expired_token_returns_none(self):
        from datetime import datetime, timedelta, timezone
        now = datetime.now(timezone.utc)
        payload = {
            "sub": USER_ID,
            "email": EMAIL,
            "type": "access",
            "iat": now - timedelta(minutes=30),
            "exp": now - timedelta(minutes=1),
            "jti": "somejti",
        }
        expired_token = jwt.encode(payload, SECRET, algorithm=ALGORITHM)
        result = verify_token(expired_token, SECRET, expected_type="access")
        assert result is None

    def test_default_expected_type_is_access(self):
        token = create_access_token(USER_ID, EMAIL, SECRET)
        payload = verify_token(token, SECRET)
        assert payload is not None


class TestHashToken:
    def test_returns_hex_string(self):
        result = hash_token("sometoken")
        assert isinstance(result, str)
        assert len(result) == 64

    def test_deterministic(self):
        assert hash_token("abc") == hash_token("abc")

    def test_different_inputs_produce_different_hashes(self):
        assert hash_token("token1") != hash_token("token2")

    def test_matches_sha256(self):
        token = "mytoken"
        expected = hashlib.sha256(token.encode()).hexdigest()
        assert hash_token(token) == expected
