# generated by tailtest, review before committing
import importlib.util
import json
import os
import re
import sys
from unittest.mock import MagicMock, patch

import pytest

# Stub skill dependencies unavailable outside the app runtime
_skills_stub = MagicMock()
_skills_stub.SKILLS_DIR = "/fake/skills"
sys.modules.setdefault("skills", MagicMock())
sys.modules.setdefault("skills.executor", _skills_stub)
sys.modules.setdefault("skills.skillmd_parser", MagicMock())

_here = os.path.dirname(os.path.abspath(__file__))
_spec = importlib.util.spec_from_file_location(
    "composition", os.path.join(_here, "composition.py")
)
_mod = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(_mod)

detect_write_intent = _mod.detect_write_intent
extract_params_from_message = _mod.extract_params_from_message
build_composition_text = _mod.build_composition_text
_action_match_score = _mod._action_match_score


# ---------------------------------------------------------------------------
# detect_write_intent
# ---------------------------------------------------------------------------


class TestDetectWriteIntent:
    def test_returns_none_for_empty_message(self):
        assert detect_write_intent("", "myskill") is None

    def test_returns_none_for_whitespace_message(self):
        assert detect_write_intent("   ", "myskill") is None

    def test_returns_none_when_skill_is_empty(self):
        assert detect_write_intent("add a customer", "") is None

    def test_returns_none_for_pure_question(self):
        assert detect_write_intent("what customers do we have?", "myskill") is None

    def test_returns_none_for_list_request(self):
        assert detect_write_intent("show me all invoices", "myskill") is None

    def test_returns_none_when_skill_md_missing(self):
        with patch("os.path.exists", return_value=False):
            result = detect_write_intent("add a new customer called Acme", "myskill")
        assert result is None

    def test_returns_none_when_get_cached_params_returns_none(self):
        with patch("os.path.exists", return_value=True), \
             patch.object(_mod, "get_cached_params", return_value=None):
            result = detect_write_intent("add a customer", "myskill")
        assert result is None

    def test_returns_none_when_actions_is_a_list(self):
        parsed = {"actions": ["add-customer", "delete-customer"]}
        with patch("os.path.exists", return_value=True), \
             patch.object(_mod, "get_cached_params", return_value=parsed):
            result = detect_write_intent("add a customer", "myskill")
        assert result is None

    def test_returns_none_when_no_write_action_matches_threshold(self):
        parsed = {"actions": {"read-customer": {"description": "read a customer"}}}
        with patch("os.path.exists", return_value=True), \
             patch.object(_mod, "get_cached_params", return_value=parsed):
            result = detect_write_intent("add a customer", "myskill")
        assert result is None

    def test_returns_action_dict_for_write_message(self):
        parsed = {
            "actions": {
                "add-customer": {
                    "description": "add a new customer record",
                    "required": [],
                    "optional": [],
                }
            }
        }
        with patch("os.path.exists", return_value=True), \
             patch.object(_mod, "get_cached_params", return_value=parsed):
            result = detect_write_intent("add a new customer called Acme", "myskill")
        assert result is not None
        assert result["action"] == "add-customer"
        assert result["meta"] == parsed["actions"]["add-customer"]

    def test_delete_verb_triggers_write_intent(self):
        parsed = {
            "actions": {
                "delete-invoice": {
                    "description": "delete an invoice",
                    "required": [],
                    "optional": [],
                }
            }
        }
        with patch("os.path.exists", return_value=True), \
             patch.object(_mod, "get_cached_params", return_value=parsed):
            result = detect_write_intent("delete the invoice", "billing")
        assert result is not None
        assert result["action"] == "delete-invoice"

    def test_picks_best_matching_action_among_multiple(self):
        parsed = {
            "actions": {
                "add-customer": {"description": "add a customer", "required": [], "optional": []},
                "add-invoice": {"description": "add an invoice", "required": [], "optional": []},
            }
        }
        with patch("os.path.exists", return_value=True), \
             patch.object(_mod, "get_cached_params", return_value=parsed):
            result = detect_write_intent("add a new customer", "myskill")
        assert result is not None
        assert result["action"] == "add-customer"


# ---------------------------------------------------------------------------
# _action_match_score
# ---------------------------------------------------------------------------


class TestActionMatchScore:
    def test_short_action_name_no_hyphen_returns_zero(self):
        assert _action_match_score("add something", "add", {}) == 0

    def test_exact_verb_and_entity_scores_high(self):
        score = _action_match_score("add customer now", "add-customer", {})
        assert score >= 5

    def test_synonym_verb_scores(self):
        score = _action_match_score("create a new customer", "add-customer", {})
        assert score >= 2

    def test_no_verb_or_entity_match_scores_low(self):
        score = _action_match_score("list all items", "delete-invoice", {})
        assert score < 2

    def test_description_overlap_increases_score(self):
        meta_with = {"description": "submit a payment request for approval"}
        meta_without = {}
        score_with = _action_match_score("submit payment approval", "submit-payment", meta_with)
        score_without = _action_match_score("submit payment approval", "submit-payment", meta_without)
        assert score_with >= score_without

    def test_partial_entity_word_match(self):
        score = _action_match_score("update customers", "update-customer", {})
        assert score >= 1

    def test_update_synonyms(self):
        score = _action_match_score("edit the record", "update-record", {})
        assert score >= 2

    def test_cancel_synonym(self):
        score = _action_match_score("void the transaction", "cancel-transaction", {})
        assert score >= 2


# ---------------------------------------------------------------------------
# extract_params_from_message
# ---------------------------------------------------------------------------


class TestExtractParamsFromMessage:
    def test_empty_meta_returns_empty_lists(self):
        resolved, unresolved = extract_params_from_message("add something", {}, {})
        assert resolved == []
        assert unresolved == []

    def test_email_extracted_from_message(self):
        meta = {"required": [{"name": "email", "type": "string"}], "optional": []}
        resolved, unresolved = extract_params_from_message(
            "add customer with email jane@example.com", meta, {}
        )
        assert any(f["field"] == "email" and f["value"] == "jane@example.com" for f in resolved)
        assert "email" not in unresolved

    def test_required_param_unresolved_when_absent(self):
        meta = {"required": [{"name": "email", "type": "string"}], "optional": []}
        resolved, unresolved = extract_params_from_message("add a customer", meta, {})
        assert "email" in unresolved
        assert not any(f["field"] == "email" for f in resolved)

    def test_required_fields_have_higher_confidence_than_optional(self):
        meta = {
            "required": [{"name": "email", "type": "string"}],
            "optional": [{"name": "phone", "type": "string"}],
        }
        resolved, _ = extract_params_from_message(
            "add customer test@example.com phone 555-1234", meta, {}
        )
        req_entry = next((f for f in resolved if f["field"] == "email"), None)
        opt_entry = next((f for f in resolved if f["field"] == "phone"), None)
        if req_entry and opt_entry:
            assert req_entry["confidence"] > opt_entry["confidence"]

    def test_optional_params_attempted(self):
        meta = {
            "required": [],
            "optional": [{"name": "email", "type": "string"}],
        }
        resolved, _ = extract_params_from_message(
            "register with hello@example.com", meta, {}
        )
        assert any(f["field"] == "email" for f in resolved)

    def test_optional_param_source_is_inference(self):
        meta = {
            "required": [],
            "optional": [{"name": "email", "type": "string"}],
        }
        resolved, _ = extract_params_from_message("add user@example.com", meta, {})
        entry = next((f for f in resolved if f["field"] == "email"), None)
        if entry:
            assert entry["source"] == "inference"

    def test_required_param_source_is_conversation(self):
        meta = {"required": [{"name": "email", "type": "string"}], "optional": []}
        resolved, _ = extract_params_from_message("add user@example.com", meta, {})
        entry = next((f for f in resolved if f["field"] == "email"), None)
        assert entry is not None
        assert entry["source"] == "conversation"

    def test_numeric_amount_extracted(self):
        meta = {"required": [{"name": "amount", "type": "decimal"}], "optional": []}
        resolved, unresolved = extract_params_from_message(
            "create invoice for $1,250.00", meta, {}
        )
        assert any(f["field"] == "amount" and "1250" in f["value"] for f in resolved)

    def test_record_id_from_context(self):
        meta = {"required": [{"name": "record_id", "type": "string"}], "optional": []}
        resolved, unresolved = extract_params_from_message(
            "update this record", meta, {"record_id": "abc-123"}
        )
        assert any(f["field"] == "record_id" and f["value"] == "abc-123" for f in resolved)
        assert "record_id" not in unresolved

    def test_optional_params_capped_at_five(self):
        optional = [{"name": f"opt{i}", "type": "string"} for i in range(10)]
        meta = {"required": [], "optional": optional}
        resolved, _ = extract_params_from_message("some message", meta, {})
        # At most 5 optional params are attempted; resolved should be <= 5
        assert len(resolved) <= 5


# ---------------------------------------------------------------------------
# build_composition_text
# ---------------------------------------------------------------------------


class TestBuildCompositionText:
    def _parse_composition(self, text: str) -> dict:
        m = re.search(r"<composition>(.*?)</composition>", text, re.DOTALL)
        assert m is not None, "No <composition> tag found in output"
        return json.loads(m.group(1))

    def test_output_contains_composition_tags(self):
        text = build_composition_text("add-customer", "crm", [], [])
        assert "<composition>" in text
        assert "</composition>" in text

    def test_composition_json_is_valid(self):
        text = build_composition_text("add-customer", "crm", [], [])
        data = self._parse_composition(text)
        assert isinstance(data, dict)

    def test_action_and_skill_set_in_composition(self):
        data = self._parse_composition(
            build_composition_text("add-customer", "crm", [], [])
        )
        assert data["action"] == "add-customer"
        assert data["skill"] == "crm"

    def test_summary_capitalises_action_words(self):
        data = self._parse_composition(
            build_composition_text("add-customer", "crm", [], [])
        )
        assert data["summary"] == "Add Customer"

    def test_multi_word_entity_in_summary(self):
        data = self._parse_composition(
            build_composition_text("create-sales-order", "sales", [], [])
        )
        assert data["summary"] == "Create Sales Order"

    def test_show_full_form_true_when_more_than_three_unresolved(self):
        data = self._parse_composition(
            build_composition_text("add-customer", "crm", [], ["a", "b", "c", "d"])
        )
        assert data["show_full_form"] is True

    def test_show_full_form_false_when_three_or_fewer_unresolved(self):
        data = self._parse_composition(
            build_composition_text("add-customer", "crm", [], ["a", "b", "c"])
        )
        assert data["show_full_form"] is False

    def test_resolved_fields_embedded_in_composition(self):
        resolved = [
            {
                "field": "name",
                "value": "Acme Corp",
                "confidence": 0.75,
                "source": "conversation",
                "source_detail": "Extracted from message",
            }
        ]
        data = self._parse_composition(
            build_composition_text("add-customer", "crm", resolved, [])
        )
        assert data["resolved_fields"] == resolved

    def test_unresolved_fields_embedded_in_composition(self):
        data = self._parse_composition(
            build_composition_text("add-customer", "crm", [], ["name", "email"])
        )
        assert data["unresolved_fields"] == ["name", "email"]

    def test_confirmation_includes_field_value_when_resolved(self):
        resolved = [
            {
                "field": "name",
                "value": "Acme",
                "confidence": 0.75,
                "source": "conversation",
                "source_detail": "x",
            }
        ]
        data = self._parse_composition(
            build_composition_text("add-customer", "crm", resolved, [])
        )
        assert "name=Acme" in data["confirmation"]

    def test_confirmation_is_just_summary_when_no_resolved(self):
        data = self._parse_composition(
            build_composition_text("delete-invoice", "billing", [], [])
        )
        assert data["confirmation"] == "Delete Invoice?"

    def test_prompt_text_asks_to_fill_when_unresolved(self):
        text = build_composition_text("add-customer", "crm", [], ["name"])
        assert "fill in the required fields" in text

    def test_prompt_text_asks_to_review_when_all_resolved(self):
        resolved = [
            {
                "field": "name",
                "value": "Acme",
                "confidence": 0.75,
                "source": "conversation",
                "source_detail": "x",
            }
        ]
        text = build_composition_text("add-customer", "crm", resolved, [])
        assert "review and confirm" in text

    def test_confirmation_truncates_to_first_three_resolved_fields(self):
        resolved = [
            {"field": f"f{i}", "value": f"v{i}", "confidence": 0.75, "source": "conversation", "source_detail": "x"}
            for i in range(5)
        ]
        data = self._parse_composition(
            build_composition_text("add-customer", "crm", resolved, [])
        )
        # Only first 3 fields appear in confirmation string
        assert "f0=v0" in data["confirmation"]
        assert "f1=v1" in data["confirmation"]
        assert "f2=v2" in data["confirmation"]
        assert "f3=v3" not in data["confirmation"]
